name: HSGamer

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/HSGamer.yml'
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  BetterDialogs:
    uses: ./.github/workflows/maven-build.yml
    with:
      repository: 'BetterGUI-MC/BetterDialogs'
      name: 'BetterDialogs'
      java: '21'

  ExtraStorage:
    uses: ./.github/workflows/maven-build.yml
    with:
      repository: 'HSGamer/ExtraStorage'
      name: 'ExtraStorage'
      java: '21'
